#!/bin/bash

set -e

# generate a password for root.
ROOT_PASSWORD=$(pwgen -c -n -1 12)
echo "root:$ROOT_PASSWORD" | chpasswd
echo User: root Password: $ROOT_PASSWORD

chmod 775 /app/data

# create directory for bind config
mkdir -p /app/data/bind
chown -R root:bind /app/data/bind

# populate default bind configuration if it does not exist
if [ ! -d /app/data/bind/etc ]; then
	mv /etc/bind /app/data/bind/etc
fi
rm -rf /etc/bind
ln -sf /app/data/bind/etc /etc/bind

if [ ! -d /app/data/bind/lib ]; then
	mkdir -p /app/data/bind/lib
	chown root:bind /app/data/bind/lib
fi
rm -rf /var/lib/bind
ln -sf /app/data/bind/lib /var/lib/bind

# create directory for webmin
mkdir -p /app/data/webmin

# populate the default webmin configuration if it does not exist
if [ ! -d /app/data/webmin/etc ]; then
	mv /etc/webmin /app/data/webmin/etc
fi
rm -rf /etc/webmin
ln -sf /app/data/webmin/etc /etc/webmin

/etc/init.d/webmin start

mkdir -m 0775 -p /var/run/named
chown root:bind /var/run/named
/usr/sbin/named -u bind -g
