#!/bin/bash
set -e

WEBMIN_ENABLED=${WEBMIN_ENABLED:-true}

chmod 775 ${DATA_DIR}

# create directory for bind config
mkdir -p ${DATA_DIR}/bind
chown -R root:${BIND_USER} ${DATA_DIR}/bind

# populate default bind configuration if it does not exist
if [ ! -d ${DATA_DIR}/bind/etc ]; then
  mv /etc/bind ${DATA_DIR}/bind/etc
fi
rm -rf /etc/bind
ln -sf ${DATA_DIR}/bind/etc /etc/bind

if [ ! -d ${DATA_DIR}/bind/lib ]; then
  mkdir -p ${DATA_DIR}/bind/lib
  chown root:${BIND_USER} ${DATA_DIR}/bind/lib
fi
rm -rf /var/lib/bind
ln -sf ${DATA_DIR}/bind/lib /var/lib/bind

# create directory for webmin
mkdir -p ${DATA_DIR}/webmin

# populate the default webmin configuration if it does not exist
if [ ! -d ${DATA_DIR}/webmin/etc ]; then
  mv /etc/webmin ${DATA_DIR}/webmin/etc
fi
rm -rf /etc/webmin
ln -sf ${DATA_DIR}/webmin/etc /etc/webmin

if [ "${WEBMIN_ENABLED}" == "true" ]; then
  if [ -z "${ROOT_PASSWORD}" ]; then
    # generate a random password for root
    ROOT_PASSWORD=$(pwgen -c -n -1 12)
    echo User: root Password: $ROOT_PASSWORD
  fi
  echo "root:$ROOT_PASSWORD" | chpasswd

  echo "Starting webmin..."
  /etc/init.d/webmin start
fi

echo "Starting named..."
mkdir -m 0775 -p /var/run/named
chown root:${BIND_USER} /var/run/named
exec /usr/sbin/named -u ${BIND_USER} -g
