#!/bin/bash

WEBMIN_VERSION=1.680

# install webmin, use local copy .deb file if available
if [ -f /app/setup/webmin_${WEBMIN_VERSION}_all.deb ]; then
	dpkg -i /app/setup/webmin_${WEBMIN_VERSION}_all.deb
else
	wget "http://prdownloads.sourceforge.net/webadmin/webmin_${WEBMIN_VERSION}_all.deb" -P /tmp/
	dpkg -i /tmp/webmin_${WEBMIN_VERSION}_all.deb
	rm -rf /tmp/webmin_${WEBMIN_VERSION}_all.deb
fi

mkdir -p /var/run/sshd
cat > /etc/supervisor/conf.d/sshd.conf <<EOF
[program:sshd]
directory=/
command=/usr/sbin/sshd -D
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s_error.log
EOF
