#!/bin/bash

set -e

# generate a password for root.
ROOT_PASSWORD=$(pwgen -c -n -1 12)
echo "root:$ROOT_PASSWORD" | chpasswd
echo User: root Password: $ROOT_PASSWORD

# start supervisord
/usr/bin/supervisord

chown -R root:bind /app/data
mkdir -p /var/lib/bind
chown root:bind /var/lib/bind

# populate default configuration if it does not exist
if [ ! -f /var/lib/bind/named.conf ]; then
	mv /etc/bind/named.conf /var/lib/bind/
	mv /etc/bind/named.conf.options /var/lib/bind/
	mv /etc/bind/named.conf.local /var/lib/bind/
	mv /etc/bind/named.conf.default-zones /var/lib/bind/
fi

ln -sf /var/lib/bind/named.conf /etc/bind/
ln -sf /var/lib/bind/named.conf.options /etc/bind/
ln -sf /var/lib/bind/named.conf.local /etc/bind/
ln -sf /var/lib/bind/named.conf.default-zones /etc/bind/

appStart () {
	/etc/init.d/webmin start
	supervisorctl start named
	tail -F /var/log/supervisor/supervisord.log
}

appHelp () {
	echo "Available options:"
	echo " app:start          - Start the app and watch the supervisor log (default)"
	echo " app:help           - Displays the help"
	echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
	app:start)
		appStart
		;;
	app:help)
		appHelp
		;;
	*)
		if [ -x $1 ]; then
			$1
		else
			prog=$(which $1)
			if [ -n "${prog}" ] ; then
				shift 1
				$prog $@
			else
				appHelp
			fi
		fi
		;;
esac

exit 0
