#!/bin/bash

set -e

# generate a password for root.
ROOT_PASSWORD=$(pwgen -c -n -1 12)
echo "root:$ROOT_PASSWORD" | chpasswd
echo User: root Password: $ROOT_PASSWORD

# start supervisord
/usr/bin/supervisord
supervisorctl start sshd

chmod 775 /app/data
chown -R root:bind /app/data

# populate default configuration if it does not exist
if [ ! -d /app/data/etc ]; then
	mv /etc/bind /app/data/etc
fi
rm -rf /etc/bind
ln -sf /app/data/etc /etc/bind

if [ ! -d /app/data/lib ]; then
	mkdir -p /app/data/lib
	chown root:bind /app/data/lib
fi
rm -rf /var/lib/bind
ln -sf /app/data/lib /var/lib/bind

appStart () {
	supervisorctl start named
	/etc/init.d/webmin start
	tail -F /var/log/supervisor/supervisord.log
}

appHelp () {
	echo "Available options:"
	echo " app:start          - Start the app and watch the supervisor log (default)"
	echo " app:help           - Displays the help"
	echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
	app:start)
		appStart
		;;
	app:help)
		appHelp
		;;
	*)
		if [ -x $1 ]; then
			$1
		else
			prog=$(which $1)
			if [ -n "${prog}" ] ; then
				shift 1
				$prog $@
			else
				appHelp
			fi
		fi
		;;
esac

exit 0
